---
title: Arcadia Page
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: true
    social-share: true
    readtime: true
- scope:
    path: ''
  values:
    layout: page
    show-avatar: true
description: Iâ€™m an HSP INFP intuitive writer/artist, and I enjoy sharing what is helping me build a loving relationship with life and myself. 
author: Arcadia Page
show_related_posts: true
navbar-links:
  ðŸ’  About: aboutme
  ðŸ’Ž Books: https://payhip.com/ArcadiaPage
  ðŸ“˜ Topics: tags
  "\U0001F5A4 Subscribe": https://arcadiapage.substack.com/
  Resources:
  - The Quiet Room: the-quiet-room
  - Thoughts: https://arcadia.thoughts.page
  - The Blue Room: the-blue-room
  - Disclosure: https://payhip.com/ArcadiaPage/privacy-policy
avatar: "assets/img/2025ProfileDrawingFinished.png"
round-avatar: true
social-network-links:
  email: arcadia@arcadiapage.com
  rss: true
url-pretty: www.arcadiapage.com
link-tags: true
excerpt_length: 50
navbar-col: "#92BFDB"
navbar-text-col: "#FFFCF0"
navbar-border-col: "#EAEAEA"
page-col: "#FFFCF0"
link-col: "#66A0C8"
hover-col: "#C6DDE8"
footer-col: "#3171B2"
footer-text-col: "#163B66"
footer-link-col: "#92BFDB"
page-img: ""
title-separator: "-"
date_format: "%B %-d, %Y"
markdown: kramdown
highlighter: rouge
permalink: "/:year-:month-:day-:title/"
paginate: 6
paginate_path: "/page:num/"
kramdown:
  input: GFM
exclude:
- CHANGELOG.md
- CNAME
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- screenshot.png
- docs/
- vendor
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-redirect-from
